"""Add reviews table

Revision ID: 9ddfac0f877b
Revises: 5d3ff392f87a
Create Date: 2026-08-25 15:30:10.622436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ddfac0f877b'
down_revision: Union[str, Sequence[str], None] = '5d3ff392f87a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_image_id'), 'reviews', ['image_id'], unique=False)
    op.create_index(op.f('ix_reviews_post_id'), 'reviews', ['post_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_post_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_image_id'), table_name='reviews')
    op.drop_table('reviews')
    # ### end Alembic commands ###
